spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/FidsDb
    password: 4412199.Gmc
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      format_sql: true

server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

  servlet:
    context-path: /fids


SECRET: "/hyQpC5+F1753t9LfpneOn7z5uxr94XzD/90OCE7Vw3YgI1IJYJ6WbhThae13lTssJ0p1w5h6X+t+h0Z1aM2fQ=="
EXPIRATION: 900000